
#
# docker buildx build  --platform linux/arm64/v8,linux/amd64 --tag compound45/dev:wireguard-vanity-address-scratch -f Dockerfile-scratch .
#

ARG DISTRO=alpine:3.20.3

FROM compound45/dev:wireguard-vanity-address-alpine-mac AS builder

# ---
# run (binary only)
# ---
FROM scratch

# Copy over the user
COPY --from=builder /etc/passwd /etc/passwd

USER user
WORKDIR /home/user

COPY --from=builder /home/user/wireguard-vanity-address ./

ENTRYPOINT ["/home/user/wireguard-vanity-address"]
